### ISSUE TITLE
Relocating objects in the id-Editor does not work after saving

### ISSUE THREAD

**Issue by simnh** [energiekollektiv/openmod.sh-id#2]
When a object is relocated and saved, a message is thrown that every thing worked out fine. Unfortunately, if the objects have been reloaded they do not appear at the newly set, but rather old location...

**Comment by cswh** [comment]
The same accounts for deletion of objects. after clicking on Save, the message: "You just edited your scenario!" appears, but the deleted point reappeared again.

**Comment by cswh** [comment]
Deletion does not work so far. Following error after trying to save.

`127.0.0.1 - - [09/Nov/2016 22:36:00] "PUT /iD/connection/api/0.6/changeset/create HTTP/1.1" 200 -
[2016-11-09 22:36:00,965] ERROR in app: Exception on /iD/connection/api/0.6/changeset/2/upload [POST]
Traceback (most recent call last):
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/clemens/znes_clemens/openmodsh/openmod.sh/openmod/sh/web.py", line 660, in upload_changeset
    setattr(db_way, att, atts[att])
UnboundLocalError: local variable 'db_way' referenced before assignment
`
