### ISSUE TITLE
Error when hitting simulate

### ISSUE THREAD

**Issue by cswh** [energiekollektiv/openmod.sh-id#5]
```
127.0.0.1 - - [09/Nov/2016 23:23:17] "PUT /simulate?scenario=[object%20Object]&key-1=value-1&key-2=value-2 HTTP/1.1" 200 -
[2016-11-09 23:23:20,987] ERROR in app: Exception on /simulation/140665853287392 [GET]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/clemens/znes_clemens/openmodsh/openmod.sh/openmod/sh/scenario.py", line 48, in simulate
    id = int(kwargs['scenario'][1:])).first()
ValueError: invalid literal for int() with base 10: 'object Object]'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/clemens/venvs/openmod.sh/lib/python3.4/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/clemens/znes_clemens/openmodsh/openmod.sh/openmod/sh/web.py", line 241, in simulation
    result = app.results[job].get()
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
ValueError: invalid literal for int() with base 10: 'object Object]'
```

**Comment by gnn** [comment]
I checked out energiekollektiv/openmod.sh#a6c20ad and while the error is a different one on this commit, it's still caused by having `[object Object]` under the `scenario` key instead of the scenario name in `kwargs`, so I'm pretty sure it's an issue with serializing the scenario name for a request in Javascript in the iD code.
